class_balance:
  apply_smote: true
  smote_k_neighbors: 5
  smote_method: SMOTE
  undersampling: false
  use_class_weights: true
data_params:
  random_state: 42
  target_image_size: !!python/tuple
  - 224
  - 224
  test_size: 0.25
  val_size: 0.15
dimensionality_reduction:
  apply_feature_selection: true
  apply_pca: true
  feature_selection_method: univariate
  n_features_to_select: 50
  pca_variance_threshold: 0.95
ensemble_params:
  auto_weights: true
  stacking_cv: 5
  stacking_final_estimator: logistic
  voting_types:
  - hard
  - soft
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  - kappa
  plot_confusion_matrix: true
  plot_precision_recall: true
  plot_roc_curves: true
  save_predictions: true
feature_extraction:
  color_bins: 20
  extract_color_features: true
  extract_shape_features: true
  extract_statistical_features: true
  extract_texture_features: true
  glcm_angles:
  - 0
  - 45
  - 90
  - 135
  glcm_distances:
  - 1
  - 2
  - 3
  lbp_n_points: 24
  lbp_radius: 3
logging:
  level: INFO
  log_file: ./multimodal_analysis.log
  save_logs: true
model_params:
  cv_folds: 5
  hyperparameter_search: randomized
  max_iter: 1000
  n_iter_search: 100
  n_jobs: -1
  scoring_metric: f1_weighted
paths:
  images_folder: ./data/imagenes/
  metadata_file: ./data/metadata.csv
  models_folder: ./modelos/
  output_folder: ./resultados/
  plots_folder: ./graficos/
preprocessing:
  handle_missing_values: true
  imputation_strategy:
    categorical: most_frequent
    numeric: median
  missing_threshold: 0.5
  scaling_method: standard
visualization:
  dpi: 300
  interactive_plots: true
  plot_format: png
  plot_style: seaborn-v0_8
  save_plots: true
